apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitex-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saiyam1814/gitex-workshop'
    path: deploy/
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
